### ISSUE TITLE
Big maps lag way more than they should

### ISSUE THREAD

**Issue by skreem** [HungerStruck/Issues#10]
We should probably load them during the lobby period if possible.

**Comment by IT3D** [comment]
The world its self is loaded, we just need to load more chunks

**Comment by kblanks** [comment]
HungerStruck/Renaissance#69

**Comment by IT3D** [comment]
Fix is done, awaiting testing

**Comment by skreem** [comment]
@IT3D's patch worked well, slight modification to resume chunk unloading later.
